image: php:8.2

stages:
  - build
  - test

#############
job-composer:
  stage: build
  before_script:
    - echo "Running Composer Job"
  script:
    - apt-get update -yq && apt-get install -y unzip git libzip-dev
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-progress --no-suggest
  artifacts:
    untracked: true
    paths:
      - vendor/
  after_script:
    - ls -la
    - echo "After script build-${CI_COMMIT_REF_SLUG}"

#############
job-phpstan:
  stage: test
  before_script:
    - echo "Running PHPStan code quality analyse
  script:
    - php ./vendor/bin/phpstan analyze -c phpstan.neon --no-progress --error-format gitlab > phpstan.json
  artifacts:
    paths:
      - phpstan.json
    expire_in: 1 hour
    when: always
  allow_failure: true

#############
job-test:
  stage: test
  before_script:
    - echo "Running Test Job"
    - ls -lha
  script:
    - php ./vendor/bin/phpunit tests